import { Injectable } from '@angular/core';

@Injectable()
export class FeedService {

  private _data = [
    {
      type: 'image-message',
      author: 'Alexander',
      surname: 'Demeshko',
      header: 'Meet this weeks top marketer.',
      text: '"He sold over 5,000m2 of land this week alone to earn the top marketer position and claim the N10,000.00 bonus"',
      preview: 'app/feed/lands/man_cheque.jpeg',
      link: 'http://localhost:4200/#/pages/home',
      time: '15.11.2017',
      ago: '6 days ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Kostya',
      surname: 'Danovsky',
      header: 'Awesome! You just earned "N 15,790" Marketing Commission',
      text: '"Your reward on sale of 280m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: 'Today 11:55 pm',
      ago: '25 minutes ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Andrey',
      surname: 'Hrabouski',
      header: 'This rocks.  Your just got N35,760.00 Marketing Commission',
      text: '"Received  marketing commission on sale of 450m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: 'Today 9:30 pm',
      ago: '3 hrs ago',
      expanded: false,
    },{
      type: 'video-message',
      author: 'Kostya',
      surname: 'Danovsky',
      header: 'My success story',
      text: '"Watcht his video to learn how this top marketer made N1,200,000.00 in 90 days"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '18.11.2017',
      ago: '9 days ago',
      expanded: false,
    },{
      type: 'geo-message',
      author: 'Vlad',
      surname: 'Lugovsky',
      header: 'Wow!. Impressive you hauled in N5,000.00 in Membership Commission',
      text: '"The commission is on your investment of 5m2in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: 'Today 2:20 pm',
      ago: '10 hrs ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Nasta',
      surname: 'Linnie',
      header: 'Unbelievableeeeeee! You just made N12,500.00 in Marketing Commission',
      text: '"For sale of 48m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '11.11.2017',
      ago: '2 days ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Nick',
      surname: 'Cat',
      header: 'Nice, just made N800.00 in Membership Commission',
      text: '"For your investment in 48m2of land in Mile2, Amuwo-Odofin, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '11.11.2017',
      ago: '2 days ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Vlad',
      surname: 'Lugovsky',
      header: 'Hoooray,  You just hit the motherload. N35,590.00 in Marketing Commission',
      text: '"For the sale of sale of 41,800m2 of land in Maryland, Mende, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '12.11.2017',
      ago: '3 days ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Andrey',
      surname: 'Hrabouski',
      header: 'Just got N100.00 in Marketing Commission',
      text: '"For sale of 8m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '14.11.2017',
      ago: '5 days ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Nasta',
      surname: 'Linnie',
      header: 'Hipppy, you made  N1,200.00 in Marketing Commission',
      text: '"For sale of 18m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '14.11.2017',
      ago: '5 days ago',
      expanded: false,
    },{
      type: 'video-message',
      author: 'Nick',
      surname: 'Cat',
      header: 'Learn more on how to boost your membership commission',
      text: 'Watch this insightful video to learn how membership commissions work and what you can do to earn more',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '16.11.2017',
      ago: '7 days ago',
      expanded: false,
    },
  ];

  getData() {
    return this._data;
  }
}
